name: 'bert_retriever_gpt'

retriever:
    _target_: src.tokenizer.bert.Tokenizer 
    path: "klue/bert-base"

generator:
    _target_: src.tokenizer.gpt.Tokenizer 
    path: 'skt/ko-gpt-trinity-1.2B-v0.5' 
