_target_: src.datamodule.klueTC_with_kb.DataModule

name: 'klueTC_with_kb'
## dataloader parameter
batch_size: 128
shuffle: False
num_workers: 4

## data
data_dir: 'data/klueTC_100shot'     # path to folder with data
train_data: 'training.jsonl'
valid_data: 'valid.jsonl'
test_data: 'test.jsonl'
kb_data: 'kb_data.jsonl'
labels: 'label_list.txt'
#num_labels: 33

## length limit
check_length: False
max_source_length: 32
max_target_length: 256
max_kb_length: 96
